FROM nginx:alpine

COPY ./site /usr/share/nginx/html
COPY my-nginx.conf /etc/nginx/nginx.conf
COPY conf.d/ /etc/nginx/conf.d/
# Expose port 80 to access the server
EXPOSE 80

# Start NGINX in the foreground
CMD ["nginx", "-g", "daemon off;"]
