FROM eclipse-temurin:17-jdk

WORKDIR /app

# Copy your bootJar into the image
COPY build/libs/*.jar app.jar

# Expose the port your Spring Boot app uses
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
