name: Build Spring Boot BootJar

on:
  push:
    branches: [master]

jobs:
  start:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Build bootJar
        run: ./gradlew bootJar --no-daemon

      - name: Build Docker image
        run: docker build -t fhvdevops:latest -f Dockerfile-build .

  stop:
    runs-on: self-hosted
    needs: start
    steps:
      - name: Stop old container
        run: docker stop fhvdevops || true

      - name: Remove old container
        run: docker rm fhvdevops || true

  cleanup:
    runs-on: self-hosted
    needs: stop
    steps:
      - name: Run new container
        run: |
          docker run -d \
            --name fhvdevops \
            --restart unless-stopped \
            -p 8080:8080 \
            --network bridge \
            fhvdevops:latest
  test:
    runs-on: self-hosted
    needs: cleanup
    steps:
      - name: Test API endpoint
        run: |
          echo "Checking API endpoint..."
          response=$(curl -s http://10.0.40.192:8080/test)
          if [ "$response" -eq 200 ]; then
            echo "API returned success"
          else
            echo "API returned status $response"
            exit 1
          fi
